version: 0.2

phases:
  install:
    # runtime-versions:
    #   terraform: 4.0.0
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/4.0.0/terraform_4.0.0_linux_amd64.zip
      - unzip terraform.zip
      
      - terraform --version
  pre_build:
    commands:
      - echo "Executing Terraform init..."
      - terraform init
  build:
    commands:
      - echo "Executing Terraform plan..."
      - terraform plan --auto-approve
  post_build:
    commands:
      - echo "Executing Terraform apply..."
      - terraform apply --auto-approve 
